### ISSUE TITLE
请教个问题

### ISSUE THREAD

**Issue by echo-LuGuang** [Wujiaxuan007/intellij-sdk-code-samples#3]
![image](https://github.com/Wujiaxuan007/intellij-sdk-code-samples/assets/50095011/1f38cb3a-00f9-4b73-b9bf-4af51c4f3a93)

**Comment by Wujiaxuan007** [comment]
可以看下这个：https://plugins.jetbrains.com/docs/intellij/status-bar-widgets.html

**Comment by echo-LuGuang** [comment]
> 可以看下这个：https://plugins.jetbrains.com/docs/intellij/status-bar-widgets.html

ok，谢谢你！
